apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: dask
  labels:
    reana-wf: reana-wf-12345
spec:
  worker:
    replicas: 2
    spec:
      containers:
        - name: worker
          image: "ghcr.io/dask/dask:2023.1.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - dask-worker
            - --name
            - $(DASK_WORKER_NAME)
            - --dashboard
            - --dashboard-address
            - "8788"
          ports:
            - name: http-dashboard
              containerPort: 8788
              protocol: TCP
          volumeMounts:
          - name: my-volume
            mountPath: /app/output
      volumes:
      - name: my-volume
        hostPath:
          path: /home/logs
  scheduler:
    spec:
      containers:
        - name: scheduler
          image: "ghcr.io/dask/dask:2023.1.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - dask-scheduler
          ports:
            - name: tcp-comm
              containerPort: 8786
              protocol: TCP
            - name: http-dashboard
              containerPort: 8787
              protocol: TCP
          readinessProbe:
            httpGet:
              port: http-dashboard
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: http-dashboard
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 20
    service:
      type: NodePort
      selector:
        dask.org/cluster-name: dask
        dask.org/component: scheduler
      ports:
      - name: tcp-comm
        protocol: TCP
        port: 8786
        targetPort: "tcp-comm"
      - name: http-dashboard
        protocol: TCP
        port: 8787
        targetPort: "http-dashboard"
